

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-fe-plugfest
  namespace: iot-edge
  labels:
    app: edge-fe-plugfest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-fe-plugfest
  template:
    metadata:
      labels:
        app: edge-fe-plugfest
    spec:
      containers:
        - name: edge-fe-plugfest
          image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/edge-fe-sample02:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/usr/share/nginx/html/config.js"
              subPath: "config.js"
      imagePullSecrets:
        - name: ncr
      terminationGracePeriodSeconds: 10
      volumes:
          - name: config
            configMap:
              name: react-k8s-env
              items:
                - key: "web.properties"
                  path: "config.js"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-fe-plugfest-service
  namespace: iot-edge
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: edge-fe-plugfest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-k8s-env
  namespace: iot-edge
data:
  web.properties: |
    window.REACT_APP_API_BASE_URL= "http://125.6.39.164"